rosbag2_performance_benchmarking:
  benchmark_node:
    ros__parameters:
      benchmark:
        summary_result_file:  "results.csv"
        bag_root_folder:       "/tmp/rosbag2_performance_default"
        repeat_each:          1     # How many times to run each configurations (to average results)
        no_transport:         False # Whether to run storage-only or end-to-end (including transport) benchmark
        preserve_bags:        False # Whether to leave bag files after experiment (and between runs). Some configurations can take lots of space!
        parameters:                 # Each combination of parameters in this section will be benchmarked
          max_cache_size:         [100000000, 500000000]
          max_bag_size:           [0, 1000000000]
          compression:            [""]
          compression_queue_size: [1]
          compression_threads:    [0]
          storage_config_file:    [""]
