rosbag2_performance_benchmarking:
  benchmark_node:
    ros__parameters:
      benchmark:
        summary_result_file:  "results.csv"
        db_root_folder:       "rosbag2_performance_test_results"
        repeat_each:          2
        no_transport:         True
        preserve_bags:        True
        parameters:
          max_cache_size:         [10000000, 100000000]
          compression:            ["", "zstd"]
          compression_queue_size: [1]
          compression_threads:    [0]
          storage_config_file:    ["", "storage_optimized.yaml"]
