rosbag2_performance_benchmarking_node:
  ros__parameters:
    publishers: # publisher_groups parameter needs to include all the subsequent groups
      publisher_groups:
        - "10Mbs_many_frequent_small"
        - "100Mbs_large"
      wait_for_subscriptions: True
      10Mbs_many_frequent_small:
        publishers_count:   100
        topic_root:         "benchmarking_small"
        msg_size_bytes:     500
        msg_count_each:     2000
        rate_hz:            200
      100Mbs_large:
        publishers_count:   1
        topic_root:         "benchmarking_large"
        msg_size_bytes:     10000000
        msg_count_each:     100
        rate_hz:            10
        qos:  # qos settings are ignored for writer only benchmarking
          qos_depth:          5
          qos_reliability:    "best_effort" # "reliable"
          qos_durability:     "volatile" # "transient_local"
