name: Test rosbag2
on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    # Run every hour. This helps detect flakiness,
    # and broken external dependencies.
    - cron:  '0 * * * *'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-focal-latest
    steps:
    - name: Build and run tests
      id: action-ros-ci
      uses: ros-tooling/action-ros-ci@v0.2
      with:
        package-name: |
          ros2bag
          rosbag2
          rosbag2_compression
          rosbag2_compression_zstd
          rosbag2_cpp
          rosbag2_interfaces
          rosbag2_py
          rosbag2_storage
          rosbag2_storage_default_plugins
          rosbag2_test_common
          rosbag2_tests
          rosbag2_transport
          shared_queues_vendor
          sqlite3_vendor
          zstd_vendor
        target-ros2-distro: rolling
        vcs-repo-file-url: https://raw.githubusercontent.com/ros2/ros2/master/ros2.repos
        colcon-defaults: |
          {
            "build": {
              "cmake-args": [
                "-DCMAKE_CXX_FLAGS=\"-Werror\""
              ]
            },
            "test": {
              "ctest-args": ["-LE", "xfail"],
              "pytest-args": ["-m", "not xfail"]
            }
          }
    - name: Run xfail tests (not required to succeed)
      continue-on-error: true
      run: source /opt/ros/rolling/setup.sh && colcon test --packages-select $(colcon list -n --base-paths $(colcon list -p --packages-select rosbag2)/..) --packages-skip rosbag2_performance_benchmarking --event-handlers console_cohesion+ --return-code-on-test-failure --ctest-args "-L xfail" --pytest-args "-m xfail"
      working-directory: ${{ steps.action-ros-ci.outputs.ros-workspace-directory-name }}
      shell: bash
    - uses: actions/upload-artifact@v1
      with:
        name: colcon-logs
        path: ros_ws/log
