name: Test rosbag2
on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    # Run every hour. This helps detect flakiness,
    # and broken external dependencies.
    - cron:  '0 * * * *'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-focal-latest
    steps:
    - uses: ros-tooling/action-ros-ci@v0.2
      with:
        package-name: |
          ros2bag
          rosbag2_compression
          rosbag2_cpp
          rosbag2_storage
          rosbag2_storage_default_plugins
          rosbag2_transport
          shared_queues_vendor
          sqlite3_vendor
          rosbag2_test_common
          rosbag2_tests
        target-ros2-distro: rolling
        vcs-repo-file-url: https://raw.githubusercontent.com/ros2/ros2/master/ros2.repos
    - uses: actions/upload-artifact@v1
      with:
        name: colcon-logs
        path: ros_ws/log
